version: '3'

services:

  mongo:
    image: mongo
    restart: always
    env_file: ./env
    expose:
      - "27017"
    networks:
      - badass

  backend:
    build: ./backend
    container_name : backend
    env_file: ./env
    environment:
      - PORT=80
      - DB=admin
      - MONGO_HOST=mongo
    expose:
      - "80"
    networks:
      - badass
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name : frontend
    environment:
      - API_URL=http://backend
    ports:
      - 3000:3000
    networks:
      - badass
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev

networks:
  badass:
    driver: bridge
